<a href="https://colab.research.google.com/github/jinyingtld/python/blob/main/AI6103_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pythong Programming 

* Pythong is a dynamic-typed language 

    - No static type-checking

    - Flexible,succinct,though less efficient and error-prone

* Pythong has many numerical libraries 

    - They call highly efficient C/C++ libraries behind the curtain

    - LAPACK,BLAS,etc.

* Great support for deep learning

    - PyTorch,Tensorflow,Jax,Peddle,etc


# Basic of a Programming Language
* Basic syntax
* Data types
* Control structure
* Exceptions
* Threads
* Performance

# Basic Syntax

* Indentation and colon mark code blocks
* Space-based indentations and tab-based are different!
* can be super hard to debug!
```
sum = 0 
for i in range(10):
    sum += i
print(sum)

  sum is printed only once!
sum = 0 
for i in range(10):
    sum += i + i**2 + \\
    i**3
print(sum)

```

# Basic Syntax
* The return character marks end of line 
* To continue the same line of code, use the line continuation character 
\'\\'
* \# is the beginning of a comment 


# Data Type 
* Integers have no limits on their value.

In [ ]:
num = 17 ** 320
num

5541850949295918202405081540365965792972852977172558529301284205616899716558079354764343027580371566264227284283224328943216544902369965718411424586846692304538296607765149546800063770431101584710632766457476187127432980846740321915053107552729325604081860560805554161801453359513633683648277839933837013364541319950089537137346381263775423227192683614308120490424451247427541517608408025625601

# Data Type
* Integers have no limits on their value.
* Floating point numbers, however, do have limits
* 64-bit max approx $1.8 * 10^{308}$
* 32-bit max approx $3.4 * 10^{38}$
* 16-bit max approx $65,504$

***Danger of overflow and underflow during mixed precision training***

GPU - 32 bit

* Linked lists are first-class citizens

In [ ]:
nl = list()
nl.append(3)
nl.append("hello")
nl.append(8.1)
nl
# [3, 'hello', 8.1]

nl = []
nl = [3,0.2]
nl
# [3, 0.2]

[3, 0.2]

* Objects are not encapsulated.
* Pythong does not have the private keyword.
* Based on convention, anything that starts with two underscores are private.

In [ ]:
class Robot(object):
    def __init__(self):
        self.a = 123
        self._b = 223
        self.__c = 323
    
obj = Robot()
print(obj.a)
print(obj._b)
# print(obj.__c)
# 123
# 223
# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# <ipython-input-9-c06c18ac550e> in <module>()
#       8 print(obj.a)
#       9 print(obj._b)
# ---> 10 print(obj.__c)

# AttributeError: 'Robot' object has no attribute '__c'

print(obj.__dict__['_Robot__c'])
# 323
obj.__dict__ # does allow for hacks
# {'_Robot__c': 323, '_b': 223, 'a': 123}


123
223
323


{'_Robot__c': 323, '_b': 223, 'a': 123}

# Functions 
* Pythong has some aspects of a functional language
    - You can assign a functional to a variable

In [ ]:
def addone(x):
    return x+1

def addtwo(x):
    return x+2

f = addone
print(f(1)) # result is 2
f = addtwo
print(f(1)) # result is 3

2
3


# Functions 
* Pythong has some aspects of a functional language
    - You can assign a functional to a variable
    - Python provides higher-order functions like Lisp
        - map(),filter(),reduce(),etc.

In [ ]:
import functools 
def add_one_more(x,y):
    return x+y+1

f = functools.partial(add_one_more,1)
# this creates a partial function whose first argument is known but the second is not. 
print(f(2)) # result is 1+2+2=4


4


In [ ]:
def add_one(x):
    return x+1
l1 = [1,2,3,4]
l2 = list(map(add_one,l1))
print(l2)
l3 = [add_one(x) for x in l1]

# thw two results are the same but many prefer the second style

[2, 3, 4, 5]


# Multi-threading 
* You can create multiple threads in Python but they don't work as you expect.
* The Global Interpreter Lock (GIL) ensures that only one thread is executing at a time.
* It is created as a simple fix for thread safety. 
* Multi-threading leads to well-known problems of race conditions and dead locks
* Python chose a simple solution: get rid of multi-threading
* Today, there is just too much path dependency to do anything about it.

# Multi-processing 
* We can circumvent the GIL by using the multiprocessing package of Python. 
* A process has more overhead than a thread.
* All multi-threading problems, like race conditions and deadlocks,still need to be handled by the programmer.
* Those problems are inherent to any memory-sharing programs running in parallel. 
* Don't over-simplify problems.

# Pferformance 

# Numpy 

# Other Useful Pythong Packages
* MatPlotlib
    - A library for drawing diagrams in Python 
    - Visualization of any data.
    - Extremely customizable, if slightly steeper learning curve than Excel

* Scipy 
    - Scientific computing.
        
        Complementary to Numpy 
* Tensorboard
    - Visualization for the training of neural networks

# Package Managerment 
* The purpose of package management is to avoid version conflicts 
* Pip + virtualenv 
    - Does not achieve complete isolation between virtual environments
* Conda
    - Strong isolation
    - Provides an online repo of packages
    - Highly recommended 

# Numpy Arrays
* A central data structure in Numpy for vectors, matrices, and tensors.
* All data in one array have to be the same type.
* More on data types: https://numpy.org/doc/stable/reference/arrays.dtypes.html


# Creation of Arrays

In [1]:
import numpy as np 
def print_np_details(arr, name):
    print('array', name)
    print(arr)
    print('python type= ', arr.astype)
    print("numpy data type= ", arr.dtype)
    print("shape = ", arr.shape)


In [3]:
# import numpy as np 
a1D = np.array([1, 2, 3, 4]) # this creates a numpy.ndarray object from a Python list
print_np_details(a1D, "a1D")

array a1D
[1 2 3 4]
python type=  <built-in method astype of numpy.ndarray object at 0x7fe06a871f30>
numpy data type=  int64
shape =  (4,)


In [5]:
# this creates a 2d array 
a2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print_np_details(a2D, "a2D")

array a2D
[[1 2 3 4]
 [5 6 7 8]]
python type=  <built-in method astype of numpy.ndarray object at 0x7fe06a80e760>
numpy data type=  int64
shape =  (2, 4)


In [6]:
# specify the type of the array
a = np.array([127, 128, 129], dtype=np.int8)
# 8-bit integer represents value from -128 to 127
print_np_details(a, "a")

array a
[ 127 -128 -127]
python type=  <built-in method astype of numpy.ndarray object at 0x7fe06a778d00>
numpy data type=  int8
shape =  (3,)


In [7]:
# setting the data type to unsigned int 
a = np.array([127, 128, 129, 256], dtype=np.uint8)
# 8-bit unsigned integer represents value from 0 to 255
print_np_details(a, "a")

array a
[127 128 129   0]
python type=  <built-in method astype of numpy.ndarray object at 0x7fe06a81e850>
numpy data type=  uint8
shape =  (4,)


In [8]:
# setting the data type to 16-bit int 
a = np.array([127, 128, 129, 255], dtype=np.int16)
print_np_details(a, "a")

#setting the data type to 32-bit float
b = np.array([127, 128, 129, 255], dtype=np.float32) 
print_np_details(b, "b")

array a
[127 128 129 255]
python type=  <built-in method astype of numpy.ndarray object at 0x7fe06a7e83a0>
numpy data type=  int16
shape =  (4,)
array b
[127. 128. 129. 255.]
python type=  <built-in method astype of numpy.ndarray object at 0x7fe06a7aa710>
numpy data type=  float32
shape =  (4,)


In [10]:
# zero matrix 
a = np.zeros((2,3))
print_np_details(a, "a")

b = np.zeros((2,3), dtype=np.int16)
print_np_details(b, "b")

array a
[[0. 0. 0.]
 [0. 0. 0.]]
python type=  <built-in method astype of numpy.ndarray object at 0x7fe06a73be40>
numpy data type=  float64
shape =  (2, 3)
array b
[[0 0 0]
 [0 0 0]]
python type=  <built-in method astype of numpy.ndarray object at 0x7fe06a73bad0>
numpy data type=  int16
shape =  (2, 3)


In [11]:
# one matrix
a = np.ones((3, 5))
print(a)

# identity matrix
a = np.eye(4)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Slicing Arrays

In [16]:
a = np.array([[1, 2, 3],[3, 4, 6.7],[5, 9.0, 5]])
print(a)
print("selecting the first row")
print(a[0, :]) # zero based indexing 
print("select the second column")
print(a[:, 1])
print("selecting the second and the third columns")
print(a[:, 1:3])
print("selecting the second and the third rows and the 3rd column")
print(a[1:3,2])
print("selecting the entry a_{2,3}")
print(a[1,2])
print("fancy indexing first row, and second row")
print(a[[1,2]])

[[1.  2.  3. ]
 [3.  4.  6.7]
 [5.  9.  5. ]]
selecting the first row
[1. 2. 3.]
select the second column
[2. 4. 9.]
selecting the second and the third columns
[[2.  3. ]
 [4.  6.7]
 [9.  5. ]]
selecting the second and the third rows and the 3rd column
[6.7 5. ]
selecting the entry a_{2,3}
6.7
[[3.  4.  6.7]
 [5.  9.  5. ]]


In [18]:
a = np.array([[1, 2, 3],[3, 4, 6.7],[5, 9.0, 5]])
print(a)
print("assigning values to the second and the third rows and the 3rd column")
a[1:3, 2] = np.array([0.1, 0.2])
print(a)

print("assigning values to the first rows")
a[0, :] = np.array([100, 200, 300])
print(a)


[[1.  2.  3. ]
 [3.  4.  6.7]
 [5.  9.  5. ]]
assigning values to the second and the third rows and the 3rd column
[[1.  2.  3. ]
 [3.  4.  0.1]
 [5.  9.  0.2]]
assigning values to the first rows
[[1.e+02 2.e+02 3.e+02]
 [3.e+00 4.e+00 1.e-01]
 [5.e+00 9.e+00 2.e-01]]


In [20]:
a = np.array([[1, 2, 3],[3, 4, 6.7],[5, 9.0, 5]])
print("selecting the diagonal")
print(np.diagonal(a))

print("selecting the diagonal from the first and second row")
print(np.diagonal(a[0:2]))

print("assign  a new diagonal to a")
print(np.fill_diagonal(a, np.array([-4, -5, -6])))
print(a)

selecting the diagonal
[1. 4. 5.]
selecting the diagonal from the first and second row
[1. 4.]
assign  a new diagonal to a
None
[[-4.   2.   3. ]
 [ 3.  -5.   6.7]
 [ 5.   9.  -6. ]]


# Element-wise Operations

In [21]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 6, 9, 12])
print("element-wise addition")
print(a+0.2)
print("element-wise multiplication")
print(a*2)
print("element-wise division")
print(a/3)

print("element-wise addition")
print(a+b)
print("element-wise division")
print(a/b)


element-wise addition
[1.2 2.2 3.2 4.2]
element-wise multiplication
[2 4 6 8]
element-wise division
[0.33333333 0.66666667 1.         1.33333333]
element-wise addition
[ 3  8 12 16]
element-wise division
[0.5        0.33333333 0.33333333 0.33333333]


# Broadcasting